name: Build & Deploy Nuxt3 to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Nuxt3
        run: npm run build

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Sync files to VPS
        run: |
          rsync -avz --delete .output/ xver@185.84.161.119:/home/xver/accountApp/.output/

      - name: Restart app on VPS
        run: |
          ssh -o StrictHostKeyChecking=no xver@185.84.161.119 "pm2 restart accountApp || pm2 start node .output/server/index.mjs --name accountApp"
